#`version: "3.5"` указывает версию формата файла Docker Compose, который будет использоваться. В данном случае это версия 3.5. Эта версия поддерживает такие возможности, как объекты `config`, `секреты` и опции `deploy` для развертывания сервисов в рое.
version: "3.5"

#Это определение сети под названием "docker_lasp" с именем сети по умолчанию. Эта сеть может использоваться для соединения различных служб, определенных в файле Docker Compose, позволяя им взаимодействовать друг с другом.
networks:
  docker_lasp:
    name: $DEFAULT_NETWORK

services:
  #Это конфигурация Docker Compose для службы базы данных MySQL.
  mysql:
    #`env_file: - "mysql.env"` - это указание пути к файлу, содержащему переменные окружения для службы MySQL. Эти переменные окружения могут быть использованы для настройки службы MySQL, например, для установки пароля root или указания набора символов по умолчанию.
    env_file:
      - "mysql.env"
    #`image: mysql:8.0.32` указывает образ Docker, который будет использоваться для службы MySQL, с версией 8.0.32. Этот образ будет взят из Docker Hub, если он еще не присутствует на локальной машине, и будет использован для создания контейнера для службы MySQL.
    image: mysql:8.0.32
    #`shm_size: 256mb` устанавливает размер общей памяти для контейнера в 256 мегабайт. Это может быть полезно для повышения производительности при использовании некоторых приложений, таких как базы данных, которые в значительной степени полагаются на общую память.
    shm_size: 256mb
    #`ports: - "3306:3306"` сопоставляет порт 3306 контейнера MySQL с портом 3306 хост-машины. Это позволяет внешним приложениям подключаться к службе MySQL, запущенной внутри контейнера, используя IP-адрес хост-машины и порт 3306.
    ports:
      - "3306:3306"
    #`restart: always` - это опция конфигурации для Docker Compose, которая указывает, что контейнер всегда должен перезапускаться, если он останавливается по какой-либо причине, например, в результате сбоя или ручной остановки. Это гарантирует, что сервис, предоставляемый контейнером, всегда будет доступен, даже в случае неожиданных сбоев.
    restart: always
    #`volumes: - "./mysql:/var/lib/mysql"` создает постоянный том для службы MySQL. Он отображает локальный каталог `./mysql` на каталог `/var/lib/mysql` внутри контейнера. Это позволяет сохранять данные, хранящиеся в службе MySQL, даже если контейнер остановлен или удален.
    volumes:
      - "./mysql:/var/lib/mysql"
    #`container_name: mysql` устанавливает имя контейнера для службы MySQL на "mysql". Это позволяет легко идентифицировать контейнер и управлять им с помощью команд и инструментов Docker.
    container_name: mysql
    #`networks: - "docker_lasp"` определяет сеть под названием "docker_lasp" и указывает, что все службы, определенные в этом файле Docker Compose, должны быть подключены к этой сети. Это позволяет службам взаимодействовать друг с другом по сети, даже если они запущены в отдельных контейнерах.
    networks:
      - "docker_lasp"